# Generated by Django 3.2.2 on 2021-05-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_city_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='persondetails',
            name='city',
            field=models.CharField(default=-1996, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persondetails',
            name='district',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
